# -*- coding: utf-8 -*-
"""week01_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fH4aD4ty3wVWUsXqDJomko4vyLDo9Uc
"""

a = 7
b = a
print(id(a), id(b))
b = 9
# b = int(input())
#b = input()
# print(type(a), type(b))
# print(id(a), id(b))
print(a+b)
print(id(a), id(b))

number = int(input())
is_prime = True

if number <= 1:
  is_prime = False
else:
  for i in range(2, number):
    if number % i == 0:
      is_prime = False
      break
    print(i, end=" ")

if is_prime:
  print(f'{number} is prime number~')
else:
  print(f'{number} is NOT prime number!')

c = [1, -9, 7]
d = c
d[1] = 0
print(c)

print("5.7e3")
print(float("5.7e3"))  # 5.7 * (10 ** 3)
print(float("314.1592e-2")) # 314.1592 * (10 ** (-2))
print(314.1592 * (10 ** (-2)))
print(314.1592 * pow(10, -2))

#army = '우리는 국가와 국민에 "충성"을 다하는 대한민국 육군이다.'
army = '''
    우리는 국가와 국민에 "충성"을 다하는 대한민국 육군이다.
    1. 하나 우리는 자유민주주의를 수호하고 조국통일의 역군이 된다.
    2. 둘 우리는 실전과 같은 훈련으로 지상전의 승리자가 된다.
    ...
'''
print(army * 3)